// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: zitadel/application/v2/saml.proto

package application

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SAMLConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The Metadata XML is the provided or fetched metadata stored at Zitadel.
	// If either the metadata was provided as XML or when Zitadel fetched it at the provided URL,
	// it is stored here.
	MetadataXml []byte `protobuf:"bytes,1,opt,name=metadata_xml,json=metadataXml,proto3" json:"metadata_xml,omitempty"`
	// The Metadata URL is the URL where the metadata was fetched from.
	// In case the metadata was provided as raw XML, this field is empty.
	MetadataUrl string `protobuf:"bytes,2,opt,name=metadata_url,json=metadataUrl,proto3" json:"metadata_url,omitempty"`
	// LoginVersion specifies the login UI, where the user is redirected to for authentication.
	// It can be used to select a specific login UI, e.g. for embedded UIs or for custom login pages
	// hosted on any other domain.
	// If unset, the login UI is chosen by the instance default.
	LoginVersion *LoginVersion `protobuf:"bytes,3,opt,name=login_version,json=loginVersion,proto3" json:"login_version,omitempty"`
}

func (x *SAMLConfiguration) Reset() {
	*x = SAMLConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zitadel_application_v2_saml_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAMLConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAMLConfiguration) ProtoMessage() {}

func (x *SAMLConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_application_v2_saml_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAMLConfiguration.ProtoReflect.Descriptor instead.
func (*SAMLConfiguration) Descriptor() ([]byte, []int) {
	return file_zitadel_application_v2_saml_proto_rawDescGZIP(), []int{0}
}

func (x *SAMLConfiguration) GetMetadataXml() []byte {
	if x != nil {
		return x.MetadataXml
	}
	return nil
}

func (x *SAMLConfiguration) GetMetadataUrl() string {
	if x != nil {
		return x.MetadataUrl
	}
	return ""
}

func (x *SAMLConfiguration) GetLoginVersion() *LoginVersion {
	if x != nil {
		return x.LoginVersion
	}
	return nil
}

var File_zitadel_application_v2_saml_proto protoreflect.FileDescriptor

var file_zitadel_application_v2_saml_proto_rawDesc = []byte{
	0x0a, 0x21, 0x7a, 0x69, 0x74, 0x61, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x32, 0x2f, 0x73, 0x61, 0x6d, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x16, 0x7a, 0x69, 0x74, 0x61, 0x64, 0x65, 0x6c, 0x2e, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76,
	0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x7a, 0x69, 0x74,
	0x61, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x76, 0x32, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa4, 0x01, 0x0a, 0x11, 0x53, 0x41, 0x4d, 0x4c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x78, 0x6d, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x58, 0x6d, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x55, 0x72, 0x6c, 0x12, 0x49, 0x0a, 0x0d, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x7a, 0x69, 0x74, 0x61, 0x64, 0x65, 0x6c, 0x2e, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x32, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x69, 0x74, 0x61, 0x64, 0x65, 0x6c, 0x2f, 0x7a, 0x69, 0x74,
	0x61, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x32, 0x3b, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zitadel_application_v2_saml_proto_rawDescOnce sync.Once
	file_zitadel_application_v2_saml_proto_rawDescData = file_zitadel_application_v2_saml_proto_rawDesc
)

func file_zitadel_application_v2_saml_proto_rawDescGZIP() []byte {
	file_zitadel_application_v2_saml_proto_rawDescOnce.Do(func() {
		file_zitadel_application_v2_saml_proto_rawDescData = protoimpl.X.CompressGZIP(file_zitadel_application_v2_saml_proto_rawDescData)
	})
	return file_zitadel_application_v2_saml_proto_rawDescData
}

var file_zitadel_application_v2_saml_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_zitadel_application_v2_saml_proto_goTypes = []interface{}{
	(*SAMLConfiguration)(nil), // 0: zitadel.application.v2.SAMLConfiguration
	(*LoginVersion)(nil),      // 1: zitadel.application.v2.LoginVersion
}
var file_zitadel_application_v2_saml_proto_depIdxs = []int32{
	1, // 0: zitadel.application.v2.SAMLConfiguration.login_version:type_name -> zitadel.application.v2.LoginVersion
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zitadel_application_v2_saml_proto_init() }
func file_zitadel_application_v2_saml_proto_init() {
	if File_zitadel_application_v2_saml_proto != nil {
		return
	}
	file_zitadel_application_v2_login_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_zitadel_application_v2_saml_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAMLConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zitadel_application_v2_saml_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zitadel_application_v2_saml_proto_goTypes,
		DependencyIndexes: file_zitadel_application_v2_saml_proto_depIdxs,
		MessageInfos:      file_zitadel_application_v2_saml_proto_msgTypes,
	}.Build()
	File_zitadel_application_v2_saml_proto = out.File
	file_zitadel_application_v2_saml_proto_rawDesc = nil
	file_zitadel_application_v2_saml_proto_goTypes = nil
	file_zitadel_application_v2_saml_proto_depIdxs = nil
}
