// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: zitadel/object/v3alpha/object.proto

package object

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OwnerType int32

const (
	OwnerType_OWNER_TYPE_UNSPECIFIED OwnerType = 0
	OwnerType_OWNER_TYPE_SYSTEM      OwnerType = 1
	OwnerType_OWNER_TYPE_INSTANCE    OwnerType = 2
	OwnerType_OWNER_TYPE_ORG         OwnerType = 3
)

// Enum value maps for OwnerType.
var (
	OwnerType_name = map[int32]string{
		0: "OWNER_TYPE_UNSPECIFIED",
		1: "OWNER_TYPE_SYSTEM",
		2: "OWNER_TYPE_INSTANCE",
		3: "OWNER_TYPE_ORG",
	}
	OwnerType_value = map[string]int32{
		"OWNER_TYPE_UNSPECIFIED": 0,
		"OWNER_TYPE_SYSTEM":      1,
		"OWNER_TYPE_INSTANCE":    2,
		"OWNER_TYPE_ORG":         3,
	}
)

func (x OwnerType) Enum() *OwnerType {
	p := new(OwnerType)
	*p = x
	return p
}

func (x OwnerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OwnerType) Descriptor() protoreflect.EnumDescriptor {
	return file_zitadel_object_v3alpha_object_proto_enumTypes[0].Descriptor()
}

func (OwnerType) Type() protoreflect.EnumType {
	return &file_zitadel_object_v3alpha_object_proto_enumTypes[0]
}

func (x OwnerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OwnerType.Descriptor instead.
func (OwnerType) EnumDescriptor() ([]byte, []int) {
	return file_zitadel_object_v3alpha_object_proto_rawDescGZIP(), []int{0}
}

type Owner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type OwnerType `protobuf:"varint,1,opt,name=type,proto3,enum=zitadel.object.v3alpha.OwnerType" json:"type,omitempty"`
	Id   string    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Owner) Reset() {
	*x = Owner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zitadel_object_v3alpha_object_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_object_v3alpha_object_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_zitadel_object_v3alpha_object_proto_rawDescGZIP(), []int{0}
}

func (x *Owner) GetType() OwnerType {
	if x != nil {
		return x.Type
	}
	return OwnerType_OWNER_TYPE_UNSPECIFIED
}

func (x *Owner) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Instance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Property:
	//
	//	*Instance_Id
	//	*Instance_Domain
	Property isInstance_Property `protobuf_oneof:"property"`
}

func (x *Instance) Reset() {
	*x = Instance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zitadel_object_v3alpha_object_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_object_v3alpha_object_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_zitadel_object_v3alpha_object_proto_rawDescGZIP(), []int{1}
}

func (m *Instance) GetProperty() isInstance_Property {
	if m != nil {
		return m.Property
	}
	return nil
}

func (x *Instance) GetId() string {
	if x, ok := x.GetProperty().(*Instance_Id); ok {
		return x.Id
	}
	return ""
}

func (x *Instance) GetDomain() string {
	if x, ok := x.GetProperty().(*Instance_Domain); ok {
		return x.Domain
	}
	return ""
}

type isInstance_Property interface {
	isInstance_Property()
}

type Instance_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type Instance_Domain struct {
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3,oneof"`
}

func (*Instance_Id) isInstance_Property() {}

func (*Instance_Domain) isInstance_Property() {}

type Organization struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Property:
	//
	//	*Organization_OrgId
	//	*Organization_OrgDomain
	Property isOrganization_Property `protobuf_oneof:"property"`
}

func (x *Organization) Reset() {
	*x = Organization{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zitadel_object_v3alpha_object_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_object_v3alpha_object_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_zitadel_object_v3alpha_object_proto_rawDescGZIP(), []int{2}
}

func (m *Organization) GetProperty() isOrganization_Property {
	if m != nil {
		return m.Property
	}
	return nil
}

func (x *Organization) GetOrgId() string {
	if x, ok := x.GetProperty().(*Organization_OrgId); ok {
		return x.OrgId
	}
	return ""
}

func (x *Organization) GetOrgDomain() string {
	if x, ok := x.GetProperty().(*Organization_OrgDomain); ok {
		return x.OrgDomain
	}
	return ""
}

type isOrganization_Property interface {
	isOrganization_Property()
}

type Organization_OrgId struct {
	OrgId string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3,oneof"`
}

type Organization_OrgDomain struct {
	OrgDomain string `protobuf:"bytes,2,opt,name=org_domain,json=orgDomain,proto3,oneof"`
}

func (*Organization_OrgId) isOrganization_Property() {}

func (*Organization_OrgDomain) isOrganization_Property() {}

var File_zitadel_object_v3alpha_object_proto protoreflect.FileDescriptor

var file_zitadel_object_v3alpha_object_proto_rawDesc = []byte{
	0x0a, 0x23, 0x7a, 0x69, 0x74, 0x61, 0x64, 0x65, 0x6c, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x2f, 0x76, 0x33, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x7a, 0x69, 0x74, 0x61, 0x64, 0x65, 0x6c, 0x2e, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x33, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61,
	0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21,
	0x2e, 0x7a, 0x69, 0x74, 0x61, 0x64, 0x65, 0x6c, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e,
	0x76, 0x33, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x42,
	0x0f, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x03, 0xf8, 0x42, 0x01,
	0x22, 0x59, 0x0a, 0x0c, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x17, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0a, 0x6f, 0x72, 0x67,
	0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x09, 0x6f, 0x72, 0x67, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x42, 0x0f, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x03, 0xf8, 0x42, 0x01, 0x2a, 0x6b, 0x0a, 0x09, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x4f, 0x57, 0x4e, 0x45,
	0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x57, 0x4e, 0x45, 0x52, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x4f,
	0x57, 0x4e, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e,
	0x43, 0x45, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x57, 0x4e, 0x45, 0x52, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x4f, 0x52, 0x47, 0x10, 0x03, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x69, 0x74, 0x61, 0x64, 0x65, 0x6c, 0x2f, 0x7a,
	0x69, 0x74, 0x61, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x76, 0x33, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x3b, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zitadel_object_v3alpha_object_proto_rawDescOnce sync.Once
	file_zitadel_object_v3alpha_object_proto_rawDescData = file_zitadel_object_v3alpha_object_proto_rawDesc
)

func file_zitadel_object_v3alpha_object_proto_rawDescGZIP() []byte {
	file_zitadel_object_v3alpha_object_proto_rawDescOnce.Do(func() {
		file_zitadel_object_v3alpha_object_proto_rawDescData = protoimpl.X.CompressGZIP(file_zitadel_object_v3alpha_object_proto_rawDescData)
	})
	return file_zitadel_object_v3alpha_object_proto_rawDescData
}

var file_zitadel_object_v3alpha_object_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zitadel_object_v3alpha_object_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_zitadel_object_v3alpha_object_proto_goTypes = []interface{}{
	(OwnerType)(0),       // 0: zitadel.object.v3alpha.OwnerType
	(*Owner)(nil),        // 1: zitadel.object.v3alpha.Owner
	(*Instance)(nil),     // 2: zitadel.object.v3alpha.Instance
	(*Organization)(nil), // 3: zitadel.object.v3alpha.Organization
}
var file_zitadel_object_v3alpha_object_proto_depIdxs = []int32{
	0, // 0: zitadel.object.v3alpha.Owner.type:type_name -> zitadel.object.v3alpha.OwnerType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zitadel_object_v3alpha_object_proto_init() }
func file_zitadel_object_v3alpha_object_proto_init() {
	if File_zitadel_object_v3alpha_object_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zitadel_object_v3alpha_object_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Owner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zitadel_object_v3alpha_object_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zitadel_object_v3alpha_object_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Organization); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_zitadel_object_v3alpha_object_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Instance_Id)(nil),
		(*Instance_Domain)(nil),
	}
	file_zitadel_object_v3alpha_object_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Organization_OrgId)(nil),
		(*Organization_OrgDomain)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zitadel_object_v3alpha_object_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zitadel_object_v3alpha_object_proto_goTypes,
		DependencyIndexes: file_zitadel_object_v3alpha_object_proto_depIdxs,
		EnumInfos:         file_zitadel_object_v3alpha_object_proto_enumTypes,
		MessageInfos:      file_zitadel_object_v3alpha_object_proto_msgTypes,
	}.Build()
	File_zitadel_object_v3alpha_object_proto = out.File
	file_zitadel_object_v3alpha_object_proto_rawDesc = nil
	file_zitadel_object_v3alpha_object_proto_goTypes = nil
	file_zitadel_object_v3alpha_object_proto_depIdxs = nil
}
